version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: health-agent-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: agent_health_db

volumes:
  mongo_data:
